## This script contains two functions.
##  Function (1) cachematrix relies upon generation
##  of a square (2 X 2) matrix by the end user
##  Function (2) cachesolve generates and prints the 
##  inverse of the matrix generated by Function (1), cachematrix

## Start Function (1) - cachematrix 
cachematrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) inv <<- inverse
  getinverse <- function() inv
  list(set=set,
       get=get, 
       setinverse=setinverse,
       getinverse=getinverse)
}
##End of Function (1) cachematrix

## Start Function (2) - cachesolve which prints the inverse of th users 2x2 matrix
cachesolve <- function(x, ...) {
  inv <- x$getinverse()
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  data <- x$get()
  inv <- solve(data)
  x$setinverse(inv)
  inv
}
